stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  services:
    - docker:dind

  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts

  script:
    - scp -r ./ $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP:ists-website/
    - ssh $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "docker build -t ists-website:latest ists-website/"
    - ssh $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "docker run -t ists-website:latest -p localhost:8001:8000"
