stages:
  - test
  - deploy

    # test:
    #   stage: test
    #   image: python:3-stretch
    #   tags:
    #     - docker
    # 
    #   before_script:
    #     - apt-get update -y
    #     - apt-get install -y build-essential python-dev
    #     - pip3 install --upgrade pip
    #     - pip3 install -r requirements.txt
    #     - pip3 install uwsgi
    #     - export FLASK_APP=project
    #     - mkdir instance
    #     - cp config.py instance/config.py
    #     - cp -r posts instance/posts
    # 
    #   script:
    #     - uwsgi --ini uwsgi.ini &

deploy:
  stage: deploy
  image: debian:stretch
  tags:
    - docker
  only:
    - "master"

  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_IP >> ~/.ssh/known_hosts
    - echo $CONFIG_PY > config.py
    - scp -r ./ $DEPLOY_USER@$DEPLOY_IP:/home/user/ists-website

  script:
    - ssh $DEPLOY_USER@$DEPLOY_IP "docker-compose up -d --build"
